modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="things"
version="1.0.0"
displayName="things"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="exvinso, MCreator"

[[dependencies.things]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



